remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: true
  month: false
  week: false
  24 hours: false

positions:
  - Geographer
  - Geospatial Analyst
  - Cartographer
  - GIS Specialist
  - Environmental Consultant
  - Conservation Scientist
  - Sustainability Coordinator
  - Political Risk Analyst
  - Intelligence Analyst
  - International Relations Specialist
  - Program Manager
  - Global Affairs Advisor
  - Photojournalist
  - Multimedia Journalist
  - Photo Editor
  - Visual Storyteller
  - Editorial Photographer
  - Sports Photographer
  - Feature Photographer
  - Press Photographer
  - Photo Archivist
  - Digital Content Producer
  - Social Media Visual Content Creator
  - Multimedia Producer
  - Videographer
  - Photo Researcher
  - Photographic Curator
  - Exhibition Photographer
  - Conservation Photographer
  - Photographic Archivist
  - Digital Imaging Specialist
  - Collections Photographer
  - Art Documentation Photographer
  - Curatorial Photographer
  - Multimedia Specialist
  - Photographic Curator
  - Visual Media Archivist
  - Photo Researcher


locations:
  - Atlanta, GA
  - United States

apply_once_at_company: false

distance: 100

company_blacklist:
  - "Fud, Inc."

title_blacklist:

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 10000

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'
